version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=djangodb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  grushina_test_rishat:
    build: .
    command: python3 manage.py runserver 0.0.0.0:1234
    container_name: grushina_test_rishat
    environment:
      - DATABASE_URL
    volumes:
      - .:/code
    ports:
      - "1234:1234"
    depends_on:
      - db